# Generated by Django 5.2.8 on 2026-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
